name: Stable Release Step 1 - Create PR

on:
  workflow_dispatch:
  # schedule:
  # - cron: "0 10 15 * *"
jobs:
  create-release-pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: create pull request
      run: | 
        gh pr create -B stable -H dev-branch --title "Stable Release PR - $(date '+%Y-%m-%d')" --body "Pull Request for creating the latest stable release from staged security fixes, bug fixes, and minor enhancements in dev-branch. Created as needed or monthly on 15th of every month, released once tests are passing"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
