name: Stable Release Step 3 - Tag and Release

on:
    workflow_dispatch:

jobs:
  Tag-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out code to release
      uses: actions/checkout@v4
    - name: Tag and release
      run: |
        echo 'find the version to create as a tag'
        tag=$(cat packages/web/lib/fog/system.class.php | grep -i 'FOG_VERSION' | grep -oP "(?<=define\('FOG_VERSION', ')[^']+(?='\))")
        echo 'create the tag and release probably like...'
        gh release create $tag --latest --generate-notes --target stable
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# on merge of monthly release pr
# get/calculate current version
# create tag of current version
# create release of new tag
# generate release notes
# send announcements?
