name: Stable Release Step 3 - Tag and Release

on:
    workflow_dispatch:
    pull_request:
        branches:
          - stable
          - dev-branch
        types:
          - closed
          
jobs:
  Tag-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out code to release
      uses: actions/checkout@v4
          fetch-depth:0
    - name: Tag and release
      run: |
        echo 'find the version to create as a tag'
        system_file="$(git rev-parse --show-toplevel)/packages/web/lib/fog/system.class.php"
        tag=$(grep "define('FOG_VERSION'" $system_file | sed "s/.*FOG_VERSION', '\([^']*\)');/\1/")
        echo 'create the tag and release...'
        gh release create $tag --latest --generate-notes --target stable
        echo 'sync dev-branch with stable branch (merge stable into dev-branch)...'
        git pull origin dev-branch
        git checkout dev-branch
        git merge stable --commit -m "merge stable - ${tag} into dev"
        git push -u origin dev-branch
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

# on merge of monthly release pr
# get/calculate current version
# create tag of current version
# create release of new tag
# generate release notes
# send announcements?
